---
- name: Ensure web server is updated
  hosts: all
  become: yes

  tasks:
  - name: Ensure git is installed
    package:
       name: git
       state: present
  - name: Ensure Ecomm is deployed
    git:
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html
...
